apiVersion: apps/v1
kind: Deployment
metadata:
   name: www-staging
spec:
  selector:
    matchLabels:
      app: www
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: www
    spec:
      containers:
      - name: www-staging
        image: 258846817560.dkr.ecr.us-east-2.amazonaws.com/frontend/staging-enterprise:20190220.01
        imagePullPolicy: Always
        resources:
          limits:
            memory: "256Mi"
          requests:
            memory: "128Mi"
        ports:
          - containerPort: 80
        readinessProbe:
          httpGet:
             path: /
             port: 80
          initialDelaySeconds: 7
          periodSeconds: 7
          successThreshold: 1